const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#5865f2",
    background: "#f2f3f5",
    foreground: "#060607",
    card: "#ffffff",
    cardForeground: "#060607",
    primary: "#5865f2",
    primaryForeground: "#ffffff",
    secondary: "#e3e5e8",
    secondaryForeground: "#060607",
    muted: "#e3e5e8",
    mutedForeground: "#4e5058",
    accent: "#5865f2",
    accentForeground: "#ffffff",
    destructive: "#da373c",
    destructiveForeground: "#ffffff",
    success: "#23a55a",
    successForeground: "#ffffff",
    warning: "#f0b232",
    warningForeground: "#ffffff",
    border: "#d4d7dc",
    input: "#e3e5e8",
    surface: "#ebedef",
  },
  dark: {
    text: "#dbdee1",
    tint: "#5865f2",
    background: "#0d0f11",
    foreground: "#dbdee1",
    card: "#1e2124",
    cardForeground: "#dbdee1",
    primary: "#5865f2",
    primaryForeground: "#ffffff",
    secondary: "#2b2d31",
    secondaryForeground: "#dbdee1",
    muted: "#2b2d31",
    mutedForeground: "#80848e",
    accent: "#5865f2",
    accentForeground: "#ffffff",
    destructive: "#da373c",
    destructiveForeground: "#ffffff",
    success: "#23a55a",
    successForeground: "#ffffff",
    warning: "#f0b232",
    warningForeground: "#ffffff",
    border: "#3b3d44",
    input: "#2b2d31",
    surface: "#2b2d31",
  },
  radius: 12,
};

export default colors;
